### ISSUE TITLE
增加代理转发的功能，不影响游戏加速器和VPN

### ISSUE THREAD

**Issue by shaonianla1997** [HaoDong108/DouyinBarrageGrab#10]
VPN和加速器都是使用的系统代理，如果这时候再启动弹幕助手，VPm和加速器的代理就失效了。能不能增加一项功能，在启动弹幕服务之前，判断一下系统代理的开启情况，如果开启状态，就获取当前代理的ip地址，再覆盖设置8888的系统代理，然后再启动弹幕的代理服务，将过滤地址以外的请求全部转发到前面获取的ip地址，这样就不会影响加速器和vpn了。

**Comment by ape-byte** [comment]
后续我可以尝试转发流量给代理程序，现在最新版本可配置不占用系统代理，你可以使用-proxy 参数启动浏览器获取弹幕
