### ISSUE TITLE
软件自动加入的代理会导致无法上网的问题？

### ISSUE THREAD

**Issue by skeras** [HaoDong108/DouyinBarrageGrab#3]
您好，
    感谢您开源的软件，我在使用中发现软件自动加入的代理会导致无法上网的问题，请问这个问题如何解决？谢谢

**Comment by wiatingpub** [comment]
我也遇见了

**Comment by ape-byte** [comment]
这一般是代理程序退出后，系统代理没有关掉的问题，你只需要进入系统设置关闭即可

**Comment by wiatingpub** [comment]
不是哈，我是用代码的模式启动程序，除了拦截不到信息外，浏览器什么的也无法上网。但是，用你给的exe包跑是没问题的，能上网也可以拦截信息。

**Comment by ape-byte** [comment]
总之，检查系统代理即可。如果你发现程序正常关闭后系统代理仍然处于打开状态，请反馈

**Comment by ape-byte** [comment]
如果系统代理和程序都关了，你仍然无法上网，那建议你尝试修复DNS
